/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#e8eaef',
        'secondary': '#4b5563',
        'inverse-primary': '#2e5bff',
        'on-primary-fixed': '#001356',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e8ecf4',
        'primary': '#2e5bff',
        'surface-dim': '#e2e6ef',
        'surface-bright': '#ffffff',
        'on-tertiary-container': '#ffffff',
        'outline-variant': '#9ca3af',
        'on-error-container': '#7f1d1d',
        'outline': '#d1d5db',
        'tertiary': '#d71a18',
        'on-surface': '#1a1a1c',
        'background': '#f4f6fa',
        'on-primary': '#ffffff',
        'inverse-surface': '#1a1a1c',
        'primary-container': '#2e5bff',
        'on-secondary-container': '#374151',
        'surface-variant': '#f0f2f7',
        'surface-container': '#f0f2f7',
        'secondary-container': '#e5e7eb',
        'tertiary-container': '#d71a18',
        'on-primary-container': '#1e3a8a',
        'surface-container-highest': '#e8ecf4',
        'on-surface-variant': '#6b7280',
        'primary-fixed': '#dde1ff',
        'surface-container-low': '#ffffff',
        'surface': '#f4f6fa',
        'on-background': '#1a1a1c',
        'error': '#dc2626',
        'primary-fixed-dim': '#b8c3ff',
        'surface-tint': '#2e5bff',
        success: '#16a34a',
        warning: '#d97706',
        info: '#2563eb',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
