CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS payroll_records (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    employee_id VARCHAR(50) NOT NULL,
    month INT NOT NULL CHECK (month BETWEEN 1 AND 12),
    year INT NOT NULL CHECK (year >= 2000),
    emp_name_snapshot VARCHAR(255) NOT NULL DEFAULT '',
    leaves FLOAT DEFAULT 0,
    lop FLOAT DEFAULT 0,
    days FLOAT DEFAULT 0,
    absents FLOAT DEFAULT 0,
    basic FLOAT DEFAULT 0,
    da FLOAT DEFAULT 0,
    basic_da FLOAT DEFAULT 0,
    hra FLOAT DEFAULT 0,
    travel FLOAT DEFAULT 0,
    children_hostel FLOAT DEFAULT 0,
    children_education FLOAT DEFAULT 0,
    mobile FLOAT DEFAULT 0,
    conveyance FLOAT DEFAULT 0,
    branch_allowance FLOAT DEFAULT 0,
    wash_allowance FLOAT DEFAULT 0,
    special_allowance FLOAT DEFAULT 0,
    training FLOAT DEFAULT 0,
    incentive FLOAT DEFAULT 0,
    total_ear_with_incen FLOAT DEFAULT 0,
    gross_sal_without_incentives FLOAT DEFAULT 0,
    gross_for_pt FLOAT DEFAULT 0,
    pf FLOAT DEFAULT 0,
    pf_3_67 FLOAT DEFAULT 0,
    pf_8_33 FLOAT DEFAULT 0,
    esi_0_75 FLOAT DEFAULT 0,
    esi_3_25 FLOAT DEFAULT 0,
    tds FLOAT DEFAULT 0,
    sal_adv FLOAT DEFAULT 0,
    additional_deduction FLOAT DEFAULT 0,
    loan FLOAT DEFAULT 0,
    advance FLOAT DEFAULT 0,
    lop_deduction FLOAT DEFAULT 0,
    company_statutory_contribution FLOAT DEFAULT 0,
    reimb_medical FLOAT DEFAULT 0,
    reimb_lta FLOAT DEFAULT 0,
    zeta_meal_voucher FLOAT DEFAULT 0,
    reimb_travel FLOAT DEFAULT 0,
    total_reimbursement FLOAT DEFAULT 0,
    epf_er FLOAT DEFAULT 0,
    net_incentive FLOAT DEFAULT 0,
    total_deductions FLOAT DEFAULT 0,
    actual_final_amount FLOAT DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dispatched_at TIMESTAMPTZ,
    UNIQUE (employee_id, month, year)
);

CREATE INDEX idx_payroll_records_period ON payroll_records (year, month);
CREATE INDEX idx_payroll_records_employee ON payroll_records (employee_id);
