/** Column headers for employee directory bulk upload / export. */
export const EMPLOYEE_DIRECTORY_HEADERS = [
  'employeeId',
  'name',
  'department',
  'mobileNo',
  'level',
  'doj',
  'yearsExperience',
  'branch',
  'designation',
  'zone',
  'basic',
  'da',
  'revisedBasicDa',
  'hra',
  'travel',
  'hostel',
  'children',
  'totalSalary',
  'mobile',
  'conveyance',
  'washAllowance',
  'branchAllowance',
  'specialAllowance',
  'training',
  'totalAllowances',
  'totalSalaryWithAllowances',
  'bankName',
  'accountNumber',
  'bankBranch',
  'ifscCode',
] as const;

/**
 * Column headers for salary directory bulk upload / export.
 * UI-only table columns (Preview, Sl. No., checkboxes, computed Total) are never exported.
 */
export const SALARY_DIRECTORY_HEADERS = [
  'employeeId',
  'empNameSnapshot',
  'leaves',
  'lop',
  'days',
  'basic',
  'da',
  'basicDa',
  'hra',
  'travel',
  'childrenHostel',
  'childrenEducation',
  'mobile',
  'conveyance',
  'branchAllowance',
  'washAllowance',
  'specialAllowance',
  'training',
  'incentive',
  'totalEarWithIncen',
  'grossSalWithoutIncentives',
  'pf',
  'pf367',
  'pf833',
  'esi075',
  'esi325',
  'tds',
  'salAdv',
  'additionalDeduction',
  'loan',
  'companyStatutoryContribution',
  'reimbMedical',
  'reimbLTA',
  'zetaMealVoucher',
  'reimbTravel',
  'totalReimbursement',
  'netIncentive',
  'totalDeductions',
  'actualFinalAmount',
  'lopDeduction',
  'epfER',
  'grossForPT',
  'advance',
  'pf367_1',
  'pf833_1',
  'absents',
] as const;
