/** Column headers for employee directory bulk upload / export. */
export const EMPLOYEE_DIRECTORY_HEADERS = [
  'employeeId',
  'name',
  'department',
  'mobileNo',
  'level',
  'doj',
  'birthday',
  'yearsExperience',
  'branch',
  'designation',
  'basic',
  'da',
  'revisedBasicDa',
  'hra',
  'travel',
  'hostel',
  'children',
  'totalSalary',
  'mobile',
  'conveyance',
  'washAllowance',
  'branchAllowance',
  'specialAllowance',
  'training',
  'totalAllowances',
  'totalSalaryWithAllowances',
  'bankName',
  'accountNumber',
  'bankBranch',
  'ifscCode',
  'zone',
] as const;

/** Column headers for EPF directory bulk upload / export (6-column template). */
export const EPF_DIRECTORY_HEADERS = [
  'employeeId',
  'doa',
  'yearsSinceDoa',
  'epfNumber',
  'uan',
  'esiNumber',
] as const;

/**
 * Column headers for salary directory bulk upload / export.
 * UI-only table columns (Preview, Sl. No., checkboxes, computed Total) are never exported.
 */
export const SALARY_DIRECTORY_HEADERS = [
  'employeeId',
  'empNameSnapshot',
  'leaves',
  'lop',
  'days',
  'basicDa',
  'hra',
  'travel',
  'childrenHostel',
  'childrenEducation',
  'mobile',
  'conveyance',
  'branchAllowance',
  'washAllowance',
  'specialAllowance',
  'training',
  'incentive',
  'totalEarWithIncen',
  'grossSalWithoutIncentives',
  'pf',
  'esi075',
  'tds',
  'salAdv',
  'additionalDeduction',
  'loan',
  'totalDeductions',
  'actualFinalAmount',
] as const;
